---

  - name: Crontab for {{ id }} 
    cron:
      name: "{{ id }}"
      minute: "*"
      job: "/opt/http.sh"

  - name: Script for {{ id }}
    template:
      src: http.sh.j2
      dest: /opt/http.sh
      mode: 0700
      