---

  - name: Crontab for {{ id }} 
    cron:
      name: "{{ id }}"
      minute: "*"
      job: "/usr/bin/python /opt/{{ id }}.py"

  - name: Script for {{ id }}
    template:
      src: http/http-{{ mode | default(http.mode) }}.py.j2
      dest: /opt/{{ id }}.py
    vars:
      url: "{{ protocol | default(http.protocol) }}://{{ host | default(http.host) }}:{{ port | default(http.port) }}/{{ path | default(http.path) }}"
      output: "{{ target | dirname}}/{{ id }}.json"

  - name: Adding javascript trigger for {{ id }}
    lineinfile:
      path: "{{ target }}"
      insertafter: '^Event.observe'
      line: "check(\"{{ id }}\")"
    changed_when: false
