---

  - name: Crontab for {{ id }} 
    cron:
      name: "{{ id }}"
      minute: "*"
      job: "/opt/{{ id }}.sh"

  - name: Script for {{ id }}
    template:
      src: http/http-{{ mode | default("json") }}.sh.j2
      dest: /opt/{{ id }}.sh
      mode: 0700
      