---

  - pip:
      name: requests

  - name: Directory with heartbeat python scripts
    file:
      path: "{{ scripts }}"
      state: directory

  - name: Directory with heartbeat outout json files
    file:
      path: "{{ target | dirname }}"
      state: directory

  - name: Copying heartbeat static file ressources
    copy:
      src: "client/{{ item }}"
      dest: "{{ target | dirname }}"
    with_items:
      - error.png
      - success.png
      - prototype.js
      - running_green.gif
      - running_red.gif
      - spinner.gif

  - name: Creating heartbeat dynamic ressource
    template:
      src: "{{ server }}.html.j2"
      dest: "{{ target }}"
    changed_when: false