---

  - name: Copying heartbeat static file ressources
    copy:
      src: "client/{{ item }}"
      dest: "{{ target | dirname }}"
    with_items:
      - error.png
      - success.png
      - prototype.js
      - running_green.gif
      - running_red.gif
      - spinner.gif

  - name: Creating heartbeat dynamic ressource
    template:
      src: "ajax.html.j2"
      dest: "{{ target }}"
    changed_when: false